# Generated by Django 3.2.25 on 2025-11-14 05:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_call_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_pain_point', models.CharField(blank=True, max_length=255, null=True)),
                ('time_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_ready', models.BooleanField(blank=True, null=True)),
                ('pain_intensity', models.CharField(blank=True, max_length=50, null=True)),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('raw_payload', djongo.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userInfo',
                'ordering': ['-created_at'],
            },
        ),
    ]
